version: 2.1  
jobs:  
  build_and_test:
    docker:
      - image: cimg/python:3.9 
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: python tests.py

  deploy:
    docker:
      - image: cimg/python:3.9  
    steps:
      - checkout
      - setup_remote_docker: 
          version: 20.10.2 # Consider updating if using a later version
      - run:
          name: Build Docker Image
          command: |
            docker build -t my-flask-app:latest .
      - run: 
          name: Login to Heroku
          command: |
            heroku login 
            heroku container:login
      - run:
          name: Push to Heroku
          command: |
            heroku container:push web -a your-heroku-app-name  
      - run:
          name: Release
          command: |
            heroku container:release web -a your-heroku-app-name

workflows: 
  main:
    jobs:
      - build_and_test
      - deploy:
          requires: [build_and_test]
          filters:
            branches:
              only: main 
